### ISSUE TITLE
slicer module

### ISSUE THREAD

**Issue by thenineteen** [fepegar/EpilepsySemiology#1]
*Click on Add and add the slicer folder of the repository: EpilepsySemiology/SemiologyVisualization/slicer*

This failed as there is no folder named *slicer*?

**Comment by fepegar** [comment]
The path was wrong, sorry. See new version of README.

**Comment by fepegar** [comment]
> Hi Fernando,
>
> despite using the corrected path-folder, loading the Semiology Visualisation module in slicer doesn't give me any options? Can't upload data nor can I see brain...
>
> regards
> ali

Do you mean the GUI is empty? Can you please open the Python console and check if there's any error message? It's the button with the Python logo (blue and yellow) on the top-right of the Slicer window.

**Comment by thenineteen** [comment]
first line in green

```
ERROR: C:\Users\ali_m\git\Semiology-Visualisation-Tool is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with svn+, git+, hg+, or bzr+).
Traceback (most recent call last):
  File "C:/Users/ali_m/AnacondaProjects/PhD/EpilepsySemiology/SemiologyVisualization/SemiologyVisualization.py", line 413, in installRepository
    import mega_analysis
ModuleNotFoundError: No module named 'mega_analysis'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/ali_m/AnacondaProjects/PhD/EpilepsySemiology/SemiologyVisualization/SemiologyVisualization.py", line 47, in setup
    self.logic.installRepository()
  File "C:/Users/ali_m/AnacondaProjects/PhD/EpilepsySemiology/SemiologyVisualization/SemiologyVisualization.py", line 418, in installRepository
    f'--editable {repoDir}',
  File "C:\Users\ali_m\AppData\Local\NA-MIC\Slicer 4.11.0-2020-03-24\bin\Python\slicer\util.py", line 2142, in pip_install
    logProcessOutput(proc)
  File "C:\Users\ali_m\AppData\Local\NA-MIC\Slicer 4.11.0-2020-03-24\bin\Python\slicer\util.py", line 2095, in logProcessOutput
    raise CalledProcessError(retcode, proc.args, output=proc.stdout, stderr=proc.stderr)
subprocess.CalledProcessError: Command '['C:/Users/ali_m/AppData/Local/NA-MIC/Slicer 4.11.0-2020-03-24/bin/../bin\\PythonSlicer.EXE', '-m', 'pip', 'install', '--editable', 'C:\\Users\\ali_m\\git\\Semiology-Visualisation-Tool']' returned non-zero exit status 1.
```

**Comment by fepegar** [comment]
This is because the module is looking for the SVT repository in `C:\Users\ali_m\git\`. As the repository is private, it can't be installed from the internet. Can you try cloning it there?

In a terminal, `cd` into your home folder (in your case, `C:\Users\ali_m`) and then:
```bash
mkdir git
cd git
git clone https://github.com/thenineteen/Semiology-Visualisation-Tool
```

Then restart Slicer and try again.

If the repo was open, this wouldn't be needed. Any chance that we can make it public? Have you asked Matt?

**Comment by thenineteen** [comment]
it works better now... but throws this:

```
No module named 'mega_analysis'

Please restart 3D Slicer and try again
Traceback (most recent call last):
  File "C:/Users/ali_m/AnacondaProjects/PhD/EpilepsySemiology/SemiologyVisualization/SemiologyVisualization.py", line 52, in setup
    self.makeGUI()
  File "C:/Users/ali_m/AnacondaProjects/PhD/EpilepsySemiology/SemiologyVisualization/SemiologyVisualization.py", line 60, in makeGUI
    self.makeSemiologiesButton()
  File "C:/Users/ali_m/AnacondaProjects/PhD/EpilepsySemiology/SemiologyVisualization/SemiologyVisualization.py", line 134, in makeSemiologiesButton
    semiologiesFormLayout.addWidget(self.getSemiologiesWidget())
  File "C:/Users/ali_m/AnacondaProjects/PhD/EpilepsySemiology/SemiologyVisualization/SemiologyVisualization.py", line 171, in getSemiologiesWidget
    get_all_semiology_terms(), self.onAutoUpdateButton)
UnboundLocalError: local variable 'get_all_semiology_terms' referenced before assignment
```

**Comment by thenineteen** [comment]
this resolves the issue as I updated the branch on the SVT repo to fix this already:

git clone --single-branch --branch <branchname> <remote-repo>

where 
* <branchname> = MegaAnalysis-March2020 
*  <remote-repo> = https://github.com/thenineteen/Semiology-Visualisation-Tool

This now means slicer installs mega_analysis module, but:

throws this error:
```
C:\Users\ali_m\AppData\Local\NA-MIC\Slicer 4.11.0-2020-03-24\lib\Python\Lib\site-packages\pandas\compat\__init__.py:117: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)
```

and 
```
No module named '_tkinter'

Please restart 3D Slicer and try again
Traceback (most recent call last):
  File "C:/Users/ali_m/AnacondaProjects/PhD/EpilepsySemiology/SemiologyVisualization/SemiologyVisualization.py", line 52, in setup
    self.makeGUI()
  File "C:/Users/ali_m/AnacondaProjects/PhD/EpilepsySemiology/SemiologyVisualization/SemiologyVisualization.py", line 60, in makeGUI
    self.makeSemiologiesButton()
  File "C:/Users/ali_m/AnacondaProjects/PhD/EpilepsySemiology/SemiologyVisualization/SemiologyVisualization.py", line 134, in makeSemiologiesButton
    semiologiesFormLayout.addWidget(self.getSemiologiesWidget())
  File "C:/Users/ali_m/AnacondaProjects/PhD/EpilepsySemiology/SemiologyVisualization/SemiologyVisualization.py", line 171, in getSemiologiesWidget
    get_all_semiology_terms(), self.onAutoUpdateButton)
UnboundLocalError: local variable 'get_all_semiology_terms' referenced before assignment
```

**Comment by fepegar** [comment]
> `Please restart 3D Slicer and try again`

When Slicer installs `mega_analysis`, it can't find it in the same session. I need to investigate that. But that's why I made that message, so it works when I restart Slicer.

> Could not import the lzma module.

> No module named '_tkinter'

I don't know why these happen. I suspect this might be a Windows issue. I'll install on Windows and try.

Now that the repo is open, I wonder what's the best strategy to install the module. There are multiple ways this can be done:
1. `pip install --editable`: this way, the module will be updated when the local repo is updated, but the path to the repo must be specified somehow.
2. `pip install --upgrade` from GitHub: I think this way we're always sure that Slicer is using the latest version of the code.

Another solution is putting everything in the same repository. That way, Slicer doesn't need to pip-install anything, just look for the modules inside the repository directory. This is probably the easiest solution.

**Comment by fepegar** [comment]
Actually I just tried on macOS and got the `tkinter` error too.

The `lzma` message comes from Pandas, and it's just a warning. Hopefully we won't need it.

**Comment by fepegar** [comment]
I think I solved it using [this solution](https://github.com/matplotlib/matplotlib/issues/9017#issuecomment-422261495). I now got an error about a YAML file not found, because I installed `mega_analysis` from GitHub. Merging the repos would solve this.

**Comment by fepegar** [comment]
Also, I think you introduced the `tkinter` when plotting. I'll disable plotting by default.

**Comment by fepegar** [comment]
The YAML file error was introduced by this commit from two days ago: https://github.com/thenineteen/Semiology-Visualisation-Tool/commit/d28bd7f80fa45fd7b83fd2f1b393c67524f11106

**Comment by fepegar** [comment]
I'll close this and open an issue in the SVT repository.
